stages:
  - deploy

image: harbor.iquantex.com/base_images/maven:3.6.1-jdk-8-alpine

before_script:
  - docker login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD}  harbor.iquantex.com

# 打完镜像会自动推送到镜像仓库, 以分支名或TAG名作为镜像的版本

deploy_k8s:
  stage: deploy
  script:
    - docker build -t harbor.iquantex.com/phoenix/phoenix-website:$CI_COMMIT_SHA . && docker push harbor.iquantex.com/phoenix/phoenix-website:$CI_COMMIT_SHA
    - helm upgrade --kubeconfig devops/phoenix-website/.kube/config-demo phoenix-website-${CI_BUILD_REF_NAME} --install --namespace=phoenix-websit-${CI_BUILD_REF_NAME} --set phoenix_website.image.tag=$CI_COMMIT_SHA devops/phoenix-website/
  only:
    - master


