# .travis.yml
language: node_js
node_js:
  - stable # use nodejs v10 LTS
branches:
  only:
    - dev
cache:
  yarn: true
script:
  - git config --global user.name "${GH_NAME}"
  - git config --global user.email "${GH_EMAIL}"
  - echo "machine github.com login ${GH_NAME} password ${GH_TOKEN}" > ~/.netrc
  - GIT_USER="${GH_NAME}" yarn deploy
