# Default values for phoenix-platform.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
nameOverride: ""
fullnameOverride: ""

## phoenix-website
phoenix_website:
  replicaCount: 1
  name: phoenix-website
  image:
    repository: harbor.iquantex.com/phoenix/phoenix-website
    tag: master
    pullPolicy: Always
  service:
    type: NodePort
  nodeSelector: {}
  tolerations: []
  affinity: {}
  resources:
    requests:
      cpu: 2
      memory: 256Mi
    limits:
      cpu: 2
      memory: 512Mi

## k8s公共配置
### 镜像拉取权限配置
imagePullSecrets: []
